import {admin,db,records,save,str,hash} from '@/lib/server';
import {initialProducts} from '@/lib/catalog';
export async function GET(req:Request){try{const products=await records('product');const seeded=await db().prepare("SELECT id FROM records WHERE id='catalog-initialized'").first();if(!seeded){await db().batch([...initialProducts.map(p=>db().prepare('INSERT OR IGNORE INTO records(id,kind,data) VALUES (?,?,?)').bind(p.id,'product',JSON.stringify(p))),db().prepare("INSERT OR IGNORE INTO records(id,kind,data) VALUES ('catalog-initialized','system','{}')")]);}
const isAdmin=await admin(req);return Response.json({products:seeded?products:await records('product'),photos:await records('photo'),admin:isAdmin,...(isAdmin?{orders:await records('order'),bookings:await records('booking'),users:(await db().prepare('SELECT id FROM users').all()).results}:{})});}catch(e){console.error(e);return Response.json({error:'The store is temporarily unavailable. Please try again.'},{status:503});}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'Invalid origin'},{status:403});const b:any=await req.json();
if(b.action==='order'||b.action==='booking'){const name=str(b.name),phone=str(b.phone,30);if(!/^[+\d\s-]{7,20}$/.test(phone))throw Error('Enter a valid phone number.');const id=crypto.randomUUID();let data:any={name,phone,notes:typeof b.notes==='string'?b.notes.slice(0,2000):'',created:new Date().toISOString(),status:'New'};
if(b.action==='order'){const address=str(b.address,500);if(!Array.isArray(b.items)||!b.items.length||b.items.length>30)throw Error('Your cart is empty or too large.');const products=await records('product');const items=b.items.map((i:any)=>{const p=products.find((p:any)=>p.id===i.id);if(!p||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>50)throw Error('A product has changed. Refresh your cart.');return {id:p.id,name:p.name,price:p.price,quantity:i.quantity};});data={...data,address,items,total:items.reduce((t:number,i:any)=>t+i.price*i.quantity,0),payment:'Cash on delivery',delivery:0};}else{const date=str(b.date,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date<new Date().toISOString().slice(0,10))throw Error('Choose today or a future date.');data={...data,service:str(b.service),date};}await save(b.action,id,data);return Response.json({id,total:data.total});}
if(!await admin(req))return Response.json({error:'Please sign in as admin.'},{status:401});
if(b.action==='product'){const price=Number(b.price);if(!Number.isFinite(price)||price<=0||price>1000000)throw Error('Enter a valid price.');await save('product',b.id||crypto.randomUUID(),{name:str(b.name),category:str(b.category),detail:str(b.detail),price,image:typeof b.image==='string'&&(/^(https:\/\/|\/api\/photo\/)/.test(b.image))?b.image:'',style:b.style||'wood'});}
else if(b.action==='photo'){if(!/^\/api\/photo\/[a-f0-9-]+$/.test(b.image))throw Error('Please upload a photo first.');await save('photo',crypto.randomUUID(),{name:str(b.name),album:str(b.album),image:b.image});}
else if(b.action==='delete'){if(!['product','photo','user'].includes(b.kind))throw Error('Invalid item.');if(b.kind==='user'){if(b.id==='test')throw Error('The primary admin cannot be removed.');await db().batch([db().prepare('DELETE FROM sessions WHERE user=?').bind(b.id),db().prepare('DELETE FROM users WHERE id=?').bind(b.id)]);}else await db().prepare('DELETE FROM records WHERE id=? AND kind=?').bind(b.id,b.kind).run();}
else if(b.action==='user'){const id=str(b.username,60),password=str(b.password,100);if(password.length<8)throw Error('Use at least 8 characters.');const salt=crypto.randomUUID();await db().prepare('INSERT INTO users(id,hash,salt) VALUES(?,?,?)').bind(id,await hash(password,salt),salt).run();}
else throw Error('Unknown action.');return Response.json({ok:true});}catch(e){console.error(e);return Response.json({error:e instanceof Error&& !e.message.includes('D1_')?e.message:'Unable to save. Check for duplicate usernames and try again.'},{status:400});}}

